apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: mateapp
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      args:
        - sleep
        - "1000" # я намагався запустити без цього аргументу, але под зависае у ребуті, так і задуманно?
