apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: mateapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: fredfredburger/todoapp:3.0.2
      ports:
        - containerPort: 8000
